import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    "Unimart — your one-stop online store for fashion, electronics, and lifestyle products. Enjoy unbeatable prices, fast delivery, and a smooth shopping experience anytime, anywhere.",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {" "}
        <Providers>
          <Toaster position="bottom-center" richColors />
          {children}
        </Providers>
      </body>
    </html>
  );
}
